/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-10-28 00:33:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Connection con = null;
	PreparedStatement pstmt = null;
	ResultSet rs = null;
	try {
		Class.forName("oracle.jdbc.OracleDriver");
		con = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe","aaaaa","1234");
		pstmt = con.prepareStatement("select * from member_tbl_01");
		rs = pstmt.executeQuery();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	header {\r\n");
      out.write("		background-color: blue;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		color: white;\r\n");
      out.write("		line-height: 100px;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("	}\r\n");
      out.write("	footer {\r\n");
      out.write("		background-color: blue;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		color: white;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		line-height: 100px;\r\n");
      out.write("		bottom: 0;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("	<h1>쇼핑몰 회원관리</h1>\r\n");
      out.write("</header>\r\n");
      out.write("<nav style=\"background-color: skyblue; height: 50px; line-height: 50px\">\r\n");
      out.write("	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"joinForm.jsp\">회원등록</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"memberForm.jsp\">회원목록조회/수정</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"SaleForm.jsp\">회원매출조회</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	<a href=\"index.jsp\">홈으로</a>\r\n");
      out.write("</nav>\r\n");
      out.write("<section>\r\n");
      out.write("	<h2 style=\"text-align: center;\">회원목록조회/수정</h2>\r\n");
      out.write("	<table border=\"1\" style=\"margin: auto; text-align: center;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>회원번호</td>\r\n");
      out.write("			<td>회원성명</td>\r\n");
      out.write("			<td>전화번호</td>\r\n");
      out.write("			<td>주소</td>\r\n");
      out.write("			<td>가입일자</td>\r\n");
      out.write("			<td>고객등급</td>\r\n");
      out.write("			<td>거주지역</td>\r\n");
      out.write("		</tr>\r\n");

	if(rs.next()) {
		do {
			String grade = "직원";
			if(rs.getString(6).equals("A")) grade="VIP";
			else if(rs.getString(6).equals("B")) grade="일반";

      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><a href=\"modForm.jsp?custno=");
      out.print(rs.getString(1) );
      out.write('"');
      out.write('>');
      out.print(rs.getString(1) );
      out.write("</a></td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(5).substring(0,10) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(grade );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");

		} while(rs.next());
	} else {
	}

      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      out.write("	<p>\r\n");
      out.write("		HRDKOREA Copyright&copy;2016 All rights reserved. Human Resources Development Service of Korea \r\n");
      out.write("	</p>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");

	} catch(Exception e) {
	} finally {
		if(rs!=null) rs.close();
		if(pstmt!=null) pstmt.close();
		if(con!=null) con.close();
	}

      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
